version: '2'
services:
    kiwitelcorechargessystem-app:
        image: kiwitelcorechargessystem
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://kiwitelcorechargessystem-mysql:3306/kiwitelcorechargessystem?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kiwitelcorechargessystem-mysql:
        extends:
            file: mysql.yml
            service: kiwitelcorechargessystem-mysql
