version: '2'
services:
    kiwicell-app:
        image: kiwicell
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://kiwicell-mysql:3306/kiwicell?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    kiwicell-mysql:
        extends:
            file: mysql.yml
            service: kiwicell-mysql
